### ISSUE TITLE
Conda support

### ISSUE THREAD

**Issue by wigging** [chemics/chemics#12]
@jan-janssen Thank you for working on the conda-forge package. Can you add the recipe into the Chemics repo and update the README with instructions for installing with conda?

**Comment by wigging** [comment]
Also, when a new version of Chemics is released does that version's recipe need to be submitted to the conda-forge/staged-recipes repository again? Or will conda-forge automatically update the Chemics conda package to the latest version?

**Comment by jan-janssen** [comment]
Conda-forge is going to create a separate repository under https://github.com/conda-forge/chemics-feedstock - currently the CI timed out with a Github API rate limit, but this should be fixed in the next hours. I am going to add you to the repository as soon as it becomes available. Finally for the new releases the process is automated so a GitHub bot is going to open an updated pull request and if the automated installation works a new package is released without any human input. But it is much easier to explain this in more detail once the repository is available.

**Comment by wigging** [comment]
Ok. Please keep me posted as things move forward on Conda-forge. I have never used it so I'm not familiar with the process.

**Comment by wigging** [comment]
I got a notification for the chemics-feedstock repository. I am now able to install `chemics` via Conda. 😄

I also noticed there are instructions in the [README](https://github.com/conda-forge/chemics-feedstock#updating-chemics-feedstock) for updating the feedstock repository. So whenever I update the Chemics package I need to also update the chemics-feedstock recipe with the new version number? Is that correct?

**Comment by jan-janssen** [comment]
By now most of the process is automated, when you update the pip package a conda bot is going to open the corresponding pull request on the conda feedstock and if the tests are passed successful the pull request is automatically merged. But we can discuss it in more detail once the next person is released.

**Comment by wigging** [comment]
I'm going to leave this Issue open until the next Chemics version. This will remind me to check on the conda-forge channel and see if it updates when the next version is released.

**Comment by wigging** [comment]
I released version 20.7 but I'm not seeing it in Conda. I guess it takes a while for Conda Forge to build everything.

**Comment by jan-janssen** [comment]
https://github.com/conda-forge/chemics-feedstock/pull/4
It sometimes take a bit of time for the bots to trigger the pull request, but as far as I can see everything worked alright and the new version should now be available.

**Comment by wigging** [comment]
It's available on conda now. Everything seems to be working well. Thank you for contributing to the project.
