### ISSUE TITLE
A Cantera Example Would be Desirable

### ISSUE THREAD

**Issue by AdityaSavara** [chemics/chemics#14]
Knowing that the chemics code has been used with Cantera, it would be desirable to have an example provided for that [full folder so that anyone with cantera can run the example].  Additionally, if there are any reports / papers where the combination was used, that will be good to provide with the example [either the actual report or a link to the report].

**Comment by wigging** [comment]
Where did you see or hear that Chemics code was used with Cantera? Since Chemics is a Python package it can be used with any Python project. You just import it like any other Python package.

**Comment by wigging** [comment]
Hey Ashi, I just now realized @AdityaSavara is your GitHub profile. Glad to see you are on here.

**Comment by AdityaSavara** [comment]
If I am not mistaken, you confirmed you had used chemics with Cantera when I asked about it by email. My experience has been that (and this is how I am, usually) if there is not an example of how to use two codes together, many (most?) potential users will not attempt to do so.

**Comment by wigging** [comment]
I don't remember what I was referring to in the email, but a recent example is where I used Chemics to calculate the [biomass composition](https://chemics.readthedocs.io/en/latest/biomass_composition.html) which was then used as the input to a Cantera reactor model. At the moment, Chemics can be used to compliment Cantera but not replace it. Ultimately, I would like for Chemics to be a complete replacement for Cantera but that will take a long time to accomplish. Especially since I'm the only person working on it.

**Comment by AdityaSavara** [comment]
My personal view is that it does not make sense to try to replace cantera rather than complementing it.  I'll just paste again what I started this issues card with:

Knowing that the chemics code has been used with Cantera, it would be desirable to have an example provided for that [full folder so that anyone with cantera can run the example]. Additionally, if there are any reports / papers where the combination was used, that will be good to provide with the example [either the actual report or a link to the report].

If you don't want to grow your user base, that's fine.  However, if you wish to, I recommend providing a zip file of such an example, within your repository or linked from it.

**Comment by AdityaSavara** [comment]
Great.

**Comment by wigging** [comment]
I added a batch reactor example to the examples repository. See the batch-reactor folder at https://github.com/chemics/examples. In the example, I use Chemics to calculate the biomass composition which is used as the initial concentration in the Cantera batch reactor model.

**Comment by wigging** [comment]
Also, I enabled the Discussions feature for the repository to encourage others to share ideas, request features, and to build a community. Not sure if it will actually get used but it's there if anyone wants to communicate in a forum instead of submitting an issue.
