### ISSUE TITLE
Question about the specific heat capacity data

### ISSUE THREAD

**Issue by Zhenetb** [chemics/chemics#25]
HI, I would like to ask a question about the specific heat capacity data,  the CAS No. of some compounds in the 4 cvs files is in date format, such as: "CH2Cl2, dichloromethane, 1975-09-02 00:00:00,...", and it should be "75-09-2". I think it may be caused by data conversion, it needs to be corrected from the original data.

**Comment by wigging** [comment]
Thank you for letting me know about this. It will take a while to correct but I'll let you know when it has been fixed.

**Comment by wigging** [comment]
The CAS numbers were exported from the Knovel (https://app.knovel.com) database for Yaws' Critical Property Data for Chemical Engineers and Chemists. The data presented online is correct but when you export it as Excel it incorrectly formats some of the CAS numbers. There is an option to export the data as CSV but it incorrectly formats the CAS numbers too. So I'll have to go through the files in chemics and fix the CAS numbers.

**Comment by wigging** [comment]
CAS numbers in the following CSV data files need to be checked and fixed:
- [x] cp-gas-inorganic.csv
- [ ] cp-gas-organic.csv
- [ ] cp-liquid-inorganic.csv
- [ ] cp-liquid-organic.csv
- [ ] k-gas-inorganic.csv
- [ ] k-gas-organic.csv
- [ ] mu-gas-inorganic.csv
- [ ] mu-gas-organic.csv

**Comment by wigging** [comment]
@Zhenetb All of the CAS numbers should be fixed in the `dev` branch. Please check the CSV files in that branch and let me know if you see anything else that needs to be fixed.

**Comment by wigging** [comment]
This issue should be fixed in the latest version which is v22.8.
