### ISSUE TITLE
Some overlap with BioSTEAM

### ISSUE THREAD

**Issue by yoelcortes** [chemics/chemics#5]
Chemics seems like a nice and useful package. I think you might be interested in BioSTEAM, especially if you are modeling unit operations. Here are some links to the docs:
https://thermosteam.readthedocs.io/en/latest/
https://biosteam.readthedocs.io/en/latest/

Here is the manuscript that introduces BioSTEAM:
https://pubs.acs.org/doi/abs/10.1021/acssuschemeng.9b0704

Thanks! :)

**Comment by wigging** [comment]
Thanks for sharing. I like the idea of BioSTEAM and I especially like that you're using Python. The project reminds me of the various projects by Caleb Bell such as https://github.com/CalebBell/thermo and https://github.com/CalebBell/fluids.

Also, the link you posted for the manuscript was broken. Here's the correct link in case anyone else reads this: https://pubs.acs.org/doi/10.1021/acssuschemeng.9b07040

**Comment by yoelcortes** [comment]
Anyone that have used thermo will definitely notice the resemblance. When I started BioSTEAM about 3 years ago, my ground zero was Caleb's thermo package. Thermosteam is basically a completely restructured and extended version of thermo for making standalone property packages that can also feed into BioSTEAM. So the legacy continues jaja.

BTW, thanks for noting the broken link and for keeping your code documented and open-source.

**Comment by wigging** [comment]
Are you part of the CABBI (https://cabbi.bio) group which is mentioned in the BioSTEAM documentation?

**Comment by wigging** [comment]
Looks like CABBI has some commonalities with the CCPC https://www.cpcbiomass.org

**Comment by yoelcortes** [comment]
Sure am. The Direct Funding Opportunity looks interesting. I just read your bio on your website and saw you are affiliated with CCPC. It would be nice to see if we can set up any collaborations later. I'll chat with my lab group and get back to you by email. Feel free to email me any ideas your group may be interested in exploring.

**Comment by wigging** [comment]
Yes, we should chat outside of GitHub regarding the CABBI and CCPC stuff. My work email is on the People page of the CCPC website.

But regarding BioSTEAM, there is some overlap to Chemics but that's common in the Python world; just look at how many visualization libraries are available for the Python community. At the moment Chemics is mainly a bunch of functions that I use for modeling fluidized bed reactors for biomass fast pyrolysis research. I eventually want to make the package similar to something like [Cantera](https://cantera.org) but that's a long term goal.

Unless you have any more comments, I think we can close this issue. Feel free to contribute to Chemics and I'll keep an eye on BioSTEAM. I do have a suggestion for BioSTEAM but I'll submit it on the repository's page.

**Comment by AdityaSavara** [comment]
Have you connected Cantera to chemics? If so, has this been used in any works?

**Comment by wigging** [comment]
@AdityaSavara I use Cantera in conjunction with Chemics but I have not "connected" them. And what do you mean by "has this been used in any works"?

**Comment by wigging** [comment]
@AdityaSavara You should submit a separate Issue for your question instead of adding to this Issue. This thread is unrelated to your question.
